### ISSUE TITLE
SELECT statement does not return the last row

### ISSUE THREAD

**Issue by jldoming** [bcolas/pentaho-cassandra-plugin#4]
I have tried with several tables.

**Comment by jldoming** [comment]
I think I found the issue in CassandraInput.java. The following check ...

```
if (rs.isExausted()) {
   logDetailed("...")
   break;
}
```
... should be moved before the **do {**

```
if (rs.isExausted()) {
   return;
}
do {  ....
```

**Comment by bcolas** [comment]
I did the modification in Master branch
Thanks
